### ISSUE TITLE
Problem with accented caracters, like éèà etc...

### ISSUE THREAD

**Issue by MadEditorDAN** [dickloraine/EmbedComicMetadata#23]
Every time there is a accent in a file name or a folder within the CBZ or CBR, the addin blocks and gives an error like this : 
![image](https://user-images.githubusercontent.com/112127826/186768395-6f8a6da6-1089-40a0-bd90-16a75a348003.png)

As I'm french speaking, I have a lot of those characters in my files, could you please have a look at what could cause this ?

**Comment by dickloraine** [comment]
I'm not 100% sure, but this seems to be a problem in calibres zipfile utility.

Looks like the filename in the header of the zipfile and the actual filename in the zipfile are encoded differently and calibre is not decoding one of the names in the right way.

Or the zipfile is not build correctly. Does it work in other applications? If you extract the files and rezip them with for example 7zip, does it work now? If so, then something with the zip file was wrong.

If the zipfile is not broken, I can't fix this unfortunatly. You would need to file a bug on [calibres bug tracker](https://bugs.launchpad.net/calibre). If they fix the issue, it would be nice to let me know.

In case I am wrong and this plugin somehow is causing the issue, let me know, best with a link to the issue on calibres tracker and I will then investigate further.

**Comment by MadEditorDAN** [comment]
Hi,  thanks for answering so quickly.

I have the exact same issue with a lot of files, of various origins, and also with ZIP files created by myself with Wirar. Those ZIP are definitly not corrupted, I had the issue with way too many files. And rebuilding them never fixed the issue. only removing the accent in the files/folder names fixed the issue.

I can't tell if the problem comes from Calibre or your add-in, but you can easily test it , just put any of those "é è ê à â" in a filename inside a cbz and you will see it :-)

**Comment by dickloraine** [comment]
Unfortunatly I don't know that much about unicode.

If I add these characters to filenames in my cbz files everything works fine. 

Have you tried zipping them with a different program than winrar? Does it only happen with zip files you created or with files from elsewhere too? The names of the files in the zip manifest are encoded differently or  are different than the filenames. And calibre appears to not be able to decode one of them properly. As far as I know european windows uses Windows-1252 encoding and sometimes utf-16. Everything else uses utf8. I am not aware that france uses anything else. Quite strange. In your screenshot you can see that the characters are different. And they seem to be not in the font calibre uses (or calibres error window just uses ascii or it is wrongly decoded there too). If there is a bug and it is not caused by winrar or something strange on your system (I can't really imagine that), then it is in calibres handling of zipfiles and/or its decoding. You would need to file a bug on the tracker I linked in the previous comment. I don't know enough about zipfiles to change the code in calibre. Calibre uses its own little zipfile utility instead of including some standart implementation and the error happens in a relatively low level component, where it calculates some byte offsets in the zipfile depending on the byte length of the filename.

**Comment by MadEditorDAN** [comment]
I have submit the "bug" in Calibre.
You can find it here : https://bugs.launchpad.net/calibre/+bug/1987953

Thanks again for your time.

**Comment by MadEditorDAN** [comment]
Hi, 

I don't know if you had time to check the Bug I submitted to Calibre, they are a quick as you are.
They gave an answer that is more directed to you. Could you please check and tell me what you think ?

**Comment by dickloraine** [comment]
I have switched to the standard python implementation for zipfiles, apart from replacing already existing files, which still uses calibres safe_replace. This seems to fix the problem. The new version is now available through calibres plugin updates. Let me know if it works now for you.

**Comment by MadEditorDAN** [comment]
I tested 3 files I knew were not working and no problem so far :-) 

I launched a full library update (Which i was never able to do...) but it takes aot of time... big library... I'll tell you if it all worked fine.

Another question, is there a way to have it update only the file without embedded Metadata, because as of now there is no way to know if a file as embedded metadata or not, so the only way is to do them all, which is not practical. An option to do only the one without any ambedded data would be neat.

Thank a lot.

**Comment by dickloraine** [comment]
Glad that it works.

For your question, this is not possible currently. It would have to be a seperate command, since the program has to know that. And to even know, if a file has metadata embedded, it has to be copied and opened regardless. The copy process takes all the time but is there to prevent corrupting the database in case something goes wrong and is the default way to ask calibre for the file. Embeding into the file costs very little time.

But what you could do for yourself for future use is making a custom column indicating if a comic has embeded metadata and setting it always after you embeded. Then you could simply filter the calibre library by comics not yet embeded which is very fast.

**Comment by MadEditorDAN** [comment]
OK. everything went fine... Thanks a Lot.
